### ISSUE TITLE
Labels in entity cards are barely readable

### ISSUE THREAD

**Issue by TheLastProject** [bbbenji/synthwave-hass#3]
![image](https://user-images.githubusercontent.com/1885159/63081402-d04e0980-bf43-11e9-9a3e-68f92ef8f785.png)

```
entities:
  - entity: input_boolean.sleep_mode
  - label: When activated
    type: section
  - entity: automation.lights_off_for_sleep_mode
    icon: 'mdi:lightbulb'
    name: Lights off
  - label: When disabled
    type: section
  - entity: automation.lights_on_for_end_of_sleep_mode
    icon: 'mdi:lightbulb'
    name: Lights on
show_header_toggle: false
title: Sleep mode
type: entities
```

Note: I don't have the JavaScript running because I installed it into HCAS, could very well be that JavaScript code fixes it, but I figured I'd make the issue anyway because it'd be neat if an install in HCAS directly makes it work super perfectly, because wow this theme is pretty.
